name: Build binaries

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build release
        run: |
          mkdir -p target/release
          touch target/release/htmlq
      - name: Archive as .tar.gz (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: tar cf htmlq-x86_64-linux.tar.gz -C target/release htmlq -I 'gzip --best'
      - name: Archive as .tar.gz (macOS)
        if: matrix.os == 'macos-latest'
        run: tar cf htmlq-x86_64-darwin.tar.gz -C target/release htmlq --use-compress-program 'gzip --best'
      - name: Archive as .zip (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: zip -9 -j htmlq-x86_64-windows.zip target/release/htmlq.exe
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            htmlq*.tar.gz
            htmlq*.zip