name: Build binary

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Build release
        run: cargo build --release
      - name: Archive as .tar.gz (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: tar cfz htmlq-x86_64-linux.tar.gz -C target/release htmlq
      - name: Archive as .tar.gz (macOS)
        if: matrix.os == 'macos-latest'
        run: tar cfz htmlq-x86_64-darwin.tar.gz -C target/release htmlq
      - name: Archive as .tar.gz (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: tar cfz htmlq-x86_64-windows.tar.gz -C target/release htmlq.exe
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: htmlq*.tar.gz